aurora-is-near/rainbow-bridge-frontend

.config.js
README.md
package.json
src/js/authNear.js
src/js/borsh/mintableTokenFactory.js
src/js/transfers.js

This removes the need for a forked contract
Relies on https://github.com/near/near-api-js/pull/426

feat: rm mint_with_json, use borsh serialization

---

.travis.yml
README.md
commitlint.config.js
package.json
yarn.lock

Add precommit hook with Husky and a Travis `lint` step to check that
commit messages are formatted according to Conventional Commits standard
This works together with `semantic-release` to push the project toward
having well-formatted release notes.

build: lint commit messages

---

commitlint.config.js

I don't know why we should care if the part after the machine-readable part has caps in it; weird default

build: Allow commit messages to use caps

---

src/css/global.css
src/html/erc20-to-near.html
src/html/select-erc20.html
src/index.html
src/js/domHelpers.js
src/js/index.js
src/js/render.js
src/js/urlParams.js

Fixes #28
The signed-in UI now shows a select box with a list of featured ERC20
tokens. Once you select one, the URL updates and the form is shown to
send one.
This also includes some usability-focused tweaks to helper functions:
* `urlParams.clear` clears the `?` from the URL when clearing last param
* `fill` keeps a cache and doesn't re-paint needlessly. This means that
when you select an ERC20 to send but then cancel, the select dropdown
still has the same item selected.
Note that filling in your own erc20 address in the URL is supported,
but the UI itself does not expose this functionality.

feat: add UI for selecting a featured ERC20

---

src/html/erc20-to-near.html
src/html/nav.html
src/js/index.js
src/js/transfers.js

This bug was introduced in 43ac0b454b2523b8380c05509b5988b4adef9548
Since ea9de4c457d49873f63a6858340447fb063d6623, there's been no logical global `window.nep21`, but `transfers` was still relying on one.

fix: undefined 'get_balance'

---

src/js/authNear.js
src/js/transfers/bridged-nep21-to-erc20/index.js

_I recommend viewing the diff [with indentation changes hidden](https://github.com/near/rainbow-bridge-frontend/pull/48/files?w=1)_
This adds some non-functional code to explore a possible way to deal with NEAR Wallet redirects. ~This approach ONLY works if the contract call does, in fact, cause a redirect.~ As of the second commit, this approach works whether or not the call results in a redirect.
The basic idea is to add ~the~ every transaction to an ~inFlightTransactions~ queue rather than sending it directly, which allows adding some metadata so that the app can identify what transaction this is for upon ~initial~ subsequent page load.
~In this particular app, that metadata is used to find the correct transfer and determine which step of the transfer it's at, so it can call the …

explore: deal with NEAR Wallet redirect using queue

---

README.md
src/html/nav.html
src/html/send-erc20.html
src/js/authEthereum.js
src/js/authNear.js
src/js/index.js
src/js/transfers/bridged-nep21-to-erc20/index.js
src/js/transfers/index.js
src/js/transfers/natural-erc20-to-nep21.js
src/js/transfers/storage.js

This implements the architectural learnings from #55 without yet adding extraneous libraries like PouchDB
BREAKING CHANGES: Requires switching to an async/await approach when calling `transfers.get` or `transfers.clear`. Removes `callback` attribute from all `transfers` functions; use `transfers.onChange` instead.

refactor(storage)!: make async, export onChanges

---

src/js/transfers/README.md

See README for an explanation of how to use the current library. I would love critical feedback on how to improve both library design and documentation.
Caveats: the code in the `transfers` directory here still has many dependencies on items that I add to `window` when users authenticate with [Ethereum](https://github.com/near/rainbow-bridge-frontend/blob/330d105bef0313cd8ccbc92ba4a821f8702f90c1/src/js/authEthereum.js) & [NEAR](https://github.com/near/rainbow-bridge-frontend/blob/330d105bef0313cd8ccbc92ba4a821f8702f90c1/src/js/authNear.js). It also still has some unresolved [TODO comments](https://github.com/near/rainbow-bridge-frontend/blob/330d105bef0313cd8ccbc92ba4a821f8702f90c1/src/js/transfers/index.js#L1). **The README added here is therefore best-case.** The final library design …

feat: document transfers library-to-be

---

src/html/erc20-form.html
src/html/erc20n-form.html
src/js/transfers/nep141~erc20/natural-erc20/getMetadata.js
src/js/utils.js

The list of ERC20 tokens and the list of associated bridged NEP141 variants was only rendered once, at page load. This meant that if you started a transfer of a certain number of tokens then started a new transfer, you would see your old balance in the token-select modals.
This fixes some caching issues in the getMetadata helpers to efficiently re-render the tokens on every `render` call.

fix: update token balances without page refresh

---

package.json
src/html/erc20-form.html
src/html/erc20n-form.html
src/html/transfers.html
src/js/transfers/nep141~erc20/bridged-nep141/getBalance.js
src/js/transfers/nep141~erc20/bridged-nep141/sendToEthereum/index.js
src/js/transfers/nep141~erc20/natural-erc20/getMetadata.js
src/js/transfers/nep141~erc20/natural-erc20/sendToNear/index.js
src/js/utils.js
yarn.lock

Fix for issues #78, #79 and #91
Users can now enter any number of tokens (including floats) and the correct decimals will be applied (usually 18 but often not the case for stable coins and others)

fix: support big number transfer amounts

---

.config.js
package.json
src/html/erc20-form.html
yarn.lock

Fix for displaying the error message from `sendToNear` in case of error: when there is already one pending transfer that is not locked (https://github.com/near/rainbow-bridge-client/pull/3) or when the user rejects signing in metamask.
@chadoh is there still a case where signing out and back in might be required ?

fix: improve error msg when sendToNear fails + Rinkeby config

---

src/html/bridge-erc20-form.html
src/html/erc20-form.html
src/html/erc20n-form.html
src/html/network-banner.html
src/html/transfers.html
src/js/authEthereum.js
src/js/authNear.js
src/js/utils.js

Trying to query metadata on the wrong eth chain will throw console errors so don't render if the selected Ethereum chain id in the wallet doesn't match the chain id of the bridge.
Also leverages the checkStatus fix in this PR https://github.com/near/rainbow-bridge-client/pull/4

fix: don't query metadata (render) if wrong eth network

---

src/css/global.css
src/html/erc20-form.html
src/html/erc20n-form.html
src/html/landing.html
src/html/transfers.html

https://hackmd.io/wKy5TKXxQqGvQVIiOdVdUg

fix: UI improvements, add faucet link

---

src/js/authEthereum.js
src/js/utils.js

Fix for https://github.com/near/rainbow-bridge-frontend/issues/110
WalletConnect tested with Metamask Mobile works.

fix: walletconnect

---

package.json
src/html/restore-transfer.html
src/html/transfers.html
src/index.html
yarn.lock

Implementation for https://github.com/near/rainbow-bridge-frontend/issues/136
Requires client release with https://github.com/near/rainbow-bridge-client/pull/10
Given an eth lock hash or a near withdraw hash, recreate a transfer object which can be finalized (mint/unlock)

feat: add transfer recovery from lock/withdraw hash

---

src/js/index.js

fixes https://github.com/near/rainbow-bridge-frontend/issues/154
https://github.com/near/rainbow-bridge-client/pull/13 fixes the interrupted near transaction.
This PR cleans the url on load so that the pending transfer can be retried if goBack was clicked from Near wallet

fix: clean url params on goBack

---

package.json
src/js/authNear.js
yarn.lock

This incorporates the change at https://github.com/near/rainbow-bridge-client/commit/9eaed466969c617e9477f2d003fc4f3f9096a474
We need to attach more than 0.006. We might only need to attach 0.02. But for now it's fastest to bump it back to 0.06. And now that faucet.paras.id gives out 0.1N, this is safe.

Increase minting deposit back to 0.06N

---

.config.js
src/html/erc20-form.html
src/html/erc20n-form.html
src/js/utils.js

If a user enters a valid custom erc20 token address, remember it in
localStorage and display it with other featured erc20s.
Put the token with a balance at the top of the list.
Fixes:
https://github.com/near/rainbow-bridge-frontend/issues/165
https://github.com/near/rainbow-bridge-frontend/issues/193

feat: remember custom erc20 addresses, display tokens with balance on top

---

src/html/incorrect-network-modal.html
src/js/authEthereum.js

Prevents the user from being stuck if the walletconnect connection
is lost and the network cannot be changed from mobile wallet, or if
mobile wallet doesn't support network change functionality.

fix: switch wallet from unsuported network

---

package.json
src/js/index.js
yarn.lock

Fix https://github.com/near/rainbow-bridge-frontend/issues/189
Wallet redirects with transactionHashes of the token deployment tx, but UI will not know that it belongs to the `bridging` of a new token without an extra param (similar to `minting`, `withdrawing`)
Requires release of https://github.com/near/rainbow-bridge-client/pull/25

fix: handle bridging redirect

---

src/html/transfers.html

Fix for https://github.com/aurora-is-near/rainbow-bridge-frontend/issues/224
Transfer can be removed before the sendToNear lock step.
Prevents deadlock if user spends the tokens in 2 places at once.

fix: enable remove transfer before lock transaction is made

---

src/html/erc20-form.html
src/html/erc20n-form.html
src/html/restore-transfer.html
src/js/domHelpers.js

After this [PR](https://github.com/aurora-is-near/rainbow-bridge-client/pull/37) is merged, we will be able to display the recovered transfer's status.
The `Searching Transfer` step was added because it will take more time to check the status of the recovered transfer.

feat: Display restored transfer status.

---

src/js/authEthereum.js

When opening Rainbow Bridge in the browser inside the [imToken wallet](https://token.im/), the wallet address will not be retrieved, making it impossible to proceed to the next step.
1. open [imToken wallet](https://token.im/), redirect to *Browser* tab.
2. Type in `https://ethereum.bridgetonear.org/` into your internal browser and visit.
3. Click on the `Connect` button to observe this issue.
The imToken wallet is injected with the exact same provider as the *metamask*, so we need to use the metamask linking method.
- When using the imToken wallet, similar to the metamask, the provider carries the additional identifier `isImToken`.
- For any other wallets or logic, no effect.
PS: Rainbow Bridge is an amazing application, imToken Wallet has a lot of users who are using it. This fix will …

fix(auth): fix provider not found when connecting to imtoken wallet
